spring:
  application:
    name: zipkin

server:
  port: 9001

management:
  security:
    enabled: false

eureka:
  client:
    region: default
    registry-fetch-interval-seconds:
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
